export const actionTypes = {
  updateSnackbar: 'UPDATE_SNACKBAR_DATA',
  closeSnackbar: 'CLOSE_SNACKBAR',
  showModal: 'SHOW_MODAL',
  hideModal: 'HIDE_MODAL',
  updateData: 'UPDATE_DATA',
  refresh: 'REFRESH',
  stopRefresh: 'STOP_REFRESH',
  showConfirmation: 'SHOW_CONFIRMATION',
  hideConfirmation: 'HIDE_CONFIRMATION',
  setAppData: 'SET_APP_DATA',
  setSelectedPhase: 'SET_SELECTED_PHASE',
  setSelectedState: 'SET_SELECTED_STATE',
  setCollapsedPhases: 'SET_COLLAPSED_PHASES',
}
